### PR TITLE
Ch home page #162156872

### PR DESCRIPTION
**Pull request by Muthembwa**
***What does this PR do?***
Create a home page
*Description of Task to be completed?*
• create link to home
• create link to flags
• create link to interventions
• create link for users without account to redirect to sign up page
• create buttons for creating flags and interventions
**How should this be manually tested?**
1. git clone https://github.com/Muthembwa/iReporter.git
2. Ch-home-page #162156872
3. run index.html page
***What are the relevant pivotal tracker stories?***
#162156872

image

### CODE REVIEW

**Comment by kirega** [comment]
It is good.

**Comment by larryTheGeek** [comment]
Awesome design

**Comment by xcixor** [comment]
looks great

**Comment by macymuhia** [comment]
Amazing, good job

**Pull request merged**
